personas/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views 

app_name='personas'
urlpatterns = [
    path('',views.index, name='index'),
 
    path('logout', views.logout,  name='logout'),
    path('detalle_proyecto2/<int:id_proyecto>/', views.detalle_proyecto2, name='detalle_proyecto2'),
    path('listado_proyectos_usuario/<int:id_usuario>/', views.listado_proyectos_usuario, name='listado_proyectos_usuario'),
    path('busqueda_proyectos/', views.busqueda_proyectos, name='busqueda_proyectos'),
    path('ultimos_proyectos/', views.ultimos_proyectos, name='ultimos_proyectos'),
    path('resultado_busqueda_proyectos/', views.resultado_busqueda_proyectos, name='resultado_busqueda_proyectos'),
    path('busqueda_personas/', views.busqueda_personas, name='busqueda_personas'),
    path('ultimos_perfiles/', views.ultimos_perfiles, name='ultimos_perfiles'),
    path('resultado_busqueda_personas/', views.resultado_busqueda_personas, name='resultado_busqueda_personas'),
    path('crear_cuenta/', views.crear_cuenta, name='crear_cuenta'),
    path('todos_proyectos/', views.todos_proyectos, name='todos_proyectos'),
    path('todas_personas/', views.todas_personas, name='todas_personas'),
    path('informar_problema/', views.informar_problema, name='informar_problema'),
  


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pshowcase/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    
    path('', include('personas.urls')),
    path('admin/', admin.site.urls),    
    path('personas/', include('personas.urls')),
    

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

personas/forms.py
from django import forms
from stdimage import StdImageField
from .models import Categoria, Herramienta, Perfil, Proyecto




#formularios de categoria
class categoria_edit_form(forms.ModelForm):

    class Meta:
        model = Categoria
        fields = ('nombre_categoria',)
        labels= {'nombre_categoria':'Nombre'}
        widgets={
            'nombre_categoria': forms.TextInput(
                attrs ={
                    'class':'form-control',
                    'placeholder':'ej: Edicion de imagen'
                }
            ),
        }


class categoria_delete_form(forms.ModelForm):

    class Meta:
        model = Categoria
        fields = ()


class categoria_create_form(forms.ModelForm):

    class Meta:
        model = Categoria
        fields = ('nombre_categoria',)
        labels= {'nombre_categoria':'Nombre'}
        widgets={
            'nombre_categoria': forms.TextInput(
                attrs ={
                    'class':'form-control',
                    'placeholder':'ej: Edicion de imagenes'
                }
            ),
        }



 

#formulario de herramientas

class herramienta_edit_form(forms.ModelForm):

    class Meta:
        model = Herramienta
        fields = ('nombre_herramienta',)
        labels= {'nombre_herramienta':'Nombre'}
        widgets={
            'nombre_herramienta': forms.TextInput(
                attrs ={
                    'class':'form-control',
                    'placeholder':'ej: Photoshop'
                }
            ),
        }

class herramienta_delete_form(forms.ModelForm):

    class Meta:
        model = Herramienta
        fields = ()

class herramienta_create_form(forms.ModelForm):

    class Meta:
        model = Herramienta
        fields = ('nombre_herramienta',)
        labels= {'nombre_herramienta':'Nombre'}
        widgets={
            'nombre_herramienta': forms.TextInput(
                attrs ={
                    'class':'form-control',
                    'placeholder':'ej: paint'
                }
            ),
        }


#formulario de perfil

class perfil_edit_form(forms.ModelForm):

    class Meta:
        model = Perfil
        fields = ('descripcion','alma_mater', 'carrera', 'retrato' )        
        widgets ={
            'alma_mater': forms.TextInput(
                attrs ={
                    'class':'form-control',
                    'placeholder':'ej: Hardvard '
                }
            ),
            'carrera': forms.TextInput(
                attrs ={
                    'class':'form-control',
                    'placeholder':'ej: Marketing'
                }
            ),
            'descripcion':forms.Textarea(
                attrs={
                    'class':'form-control',
                    'placeholder':'Cuenta algo interesante sobre ti mismo'          
                }
            )
        }



#formulario de PROYECTO

class proyecto_create_form(forms.ModelForm):

    class Meta:
        model = Proyecto
        fields = ('nombre_proyecto', 'reseña') 
        labels = {'nombre_proyecto':'Nombre'}
        widgets ={
            'nombre_proyecto': forms.TextInput(
                attrs ={
                    'class':'form-control',
                    'placeholder':'Un nombre creativo para tu proyecto'
                }
            ),
            'reseña':forms.Textarea(
                attrs={
                    'class':'form-control',
                    'placeholder':'Agrega una breve descripcion de sobre que se trata tu proyecto'          
                }
            )
        }


class proyecto_edit_form(forms.ModelForm):

    class Meta:
        model = Proyecto
        fields = ('nombre_proyecto', 'reseña')
        labels = {'nombre_proyecto':'Nombre'}
        widgets ={
            'nombre_proyecto': forms.TextInput(
                attrs ={
                    'class':'form-control',
                    'placeholder':'Un nombre creativo para tu proyecto'
                }
            ),
            'reseña':forms.Textarea(
                attrs={
                    'class':'form-control',
                    'placeholder':'Agrega una breve descripcion de sobre que se trata tu proyecto'          
                }
            )
        }

personas/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.shortcuts import HttpResponse
from personas.models import Usuario , Perfil, Proyecto, Colaboracion, Tipo_permiso, Segmento, Tipo_segmento
from personas.models import Herramienta_proyecto, Herramienta, Categoria
from django.db import IntegrityError
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import logout as do_logout
from django.contrib.auth import login as do_login, authenticate
from stdimage import StdImageField
import os
from django.conf import settings
from datetime import datetime
from django.contrib.auth.models import User
from django.core.mail import EmailMessage, send_mail



#from django.shortcuts import render_to_response


def recepcion_formulario(request):
    #modulo para captar formulario
    is_used=False

    if request.method == "POST":
        #categoria
        if request.POST.get('modelo') == 'categoria':
            is_used=True 
            #editar            
            if request.POST.get('operacion') =='editar':  
                id_aux = request.POST.get('categoria_id')
                categoria = Categoria.objects.get(id=id_aux)
                categoria.nombre_categoria =  request.POST.get('nombre_categoria')
                categoria.save()
                return redirect('/')

            if request.POST.get('operacion') =='borrar':                  
                id_aux = request.POST.get('categoria_id')
                cat_aux = Categoria.objects.get(id=id_aux)  
                cat_aux.delete()               
                return redirect('/')

            if request.POST.get('operacion') =='crear':                 
                nombre = request.POST.get('nombre_categoria')
                user_id = request.POST.get('id_usuario')
                user = Usuario.objects.get(id=user_id)
                Categoria.objects.create(nombre_categoria=nombre ,usuario= user )                                           
                return redirect('/')

        #herramienta
        if request.POST.get('modelo') == 'herramienta':   
            is_used=True         
            if request.POST.get('operacion') =='editar':                
                id_aux = request.POST.get('herramienta_id')
                herramienta = Herramienta.objects.get(id=id_aux)
                herramienta.nombre_herramienta =  request.POST.get('nombre_herramienta')
                herramienta.save()
                return redirect('/')

            if request.POST.get('operacion') =='borrar':  
                id_aux = request.POST.get('herramienta_id')
                herr_aux = Herramienta.objects.get(id=id_aux)  
                herr_aux.delete()               
                return redirect('/')

            if request.POST.get('operacion') =='crear':  
                nombre = request.POST.get('nombre_herramienta')       
                categoria_aux = Categoria.objects.get(id=request.POST.get('categoria'))                        
                Herramienta.objects.create(nombre_herramienta=nombre ,categoria=categoria_aux)  
                #return HttpResponse( categoria_aux.nombre_categoria)                                           
                return redirect('/')
        
        #perfil
        if request.POST.get('modelo') == 'perfil':   
           
            id_perfil = request.POST.get('id_perfil')
            perfil_aux = Perfil.objects.get(id=id_perfil)
            perfil_aux.descripcion =  request.POST.get('descripcion')
            perfil_aux.alma_mater =  request.POST.get('alma_mater')
            perfil_aux.carrera =  request.POST.get('carrera')        
            perfil_aux.retrato =  request.FILES.get('retrato')                                             
            perfil_aux.save()  
                  
            return redirect('/') 

        #proyectos
        if request.POST.get('modelo') == 'proyecto':
            if request.POST.get('operacion') =='crear':     
                is_used=True            
                usuario_aux = Usuario.objects.get(id= request.POST.get('id_usuario'))
                pro_aux = Proyecto.objects.create(
                    nombre_proyecto=request.POST.get('nombre_proyecto'),
                    reseña=request.POST.get('reseña'),
                    fecha_creacion=datetime.now() 
                    )
                tipo_permiso_aux = Tipo_permiso.objects.get(nombre_permiso="propietario")
                colaboracion = Colaboracion.objects.create(
                    usuario = usuario_aux, 
                    tipo_permiso= tipo_permiso_aux, 
                    proyecto=pro_aux, 
                    fecha_colaboracion=datetime.now()
                    )  
                return redirect('detalle_proyecto2/'+str(pro_aux.id))                       


        #iniciar sesion
        if request.POST.get('modelo') == 'sesion':   
            is_used=True                   
            username=request.POST.get('usuario')
            password=request.POST.get('contraseña')
            user = authenticate(username=username, password=password)
            if user is not None:
                # Hacemos el login manualmente
                do_login(request, user)
                # Y le redireccionamos a la portada
                return redirect('/')

    return is_used

def index(request):
    recepcion_formulario(request)
    return render(request, 'personas/inicio.html')


def detalle_proyecto2(request, id_proyecto):  
    recepcion_formulario(request)  
    
    proyecto_aux2 = Proyecto.objects.get(id=id_proyecto)
    lista_segmentos = list()
    tipos_segmentos = Tipo_segmento.objects.all()
    # obtener todos los segmentos en los cuales esta ese proyecto
    segmentos = Segmento.objects.filter(proyecto=proyecto_aux2).order_by('numero_segmento')
    for s in segmentos:
        segm_aux = s
        lista_segmentos.append(s)
    
    
    if request.POST.get('modelo') == 'proyecto':
        if request.POST.get('operacion') =='borrar':
            proy_aux= Proyecto.objects.get(id=request.POST.get('id_proyecto') )
            proy_aux.delete()  
            return redirect('/')

        if request.POST.get('operacion') =='editar':
            proy_aux= Proyecto.objects.get(id=request.POST.get('id_proyecto') )
            proy_aux.nombre_proyecto = request.POST.get('nombre_proyecto')
            proy_aux.reseña = request.POST.get('reseña')
            proy_aux.save()  
            return redirect('/')

    if request.POST.get('modelo') == 'colaboracion':
        if request.POST.get('operacion') =='agregar':                   
            id_permiso = request.POST.get('tipo_permiso')
            id_proyecto = request.POST.get('id_proyecto')
            usuario=request.POST.get('usuario')
            tip_permiso_aux= Tipo_permiso.objects.get(id=id_permiso)
            proyecto_aux = Proyecto.objects.get(id=id_proyecto)
            usuario_aux= Usuario.objects.get(id=usuario)
            colab_aux= Colaboracion.objects.create(usuario=usuario_aux, tipo_permiso=tip_permiso_aux, proyecto=proyecto_aux, fecha_colaboracion=datetime.now()  )
            return redirect('/')

        if request.POST.get('operacion') =='borrar':                
            id_proyecto = request.POST.get('id_proyecto')
            usuario=request.POST.get('colaborador')
            proyecto_aux = Proyecto.objects.get(id=id_proyecto)
            usuario_aux= Usuario.objects.get(id=usuario)

            colab_aux= Colaboracion.objects.get(usuario=usuario_aux, proyecto=proyecto_aux )     
            colab_aux.delete()          
            return redirect('/')
            
        if request.POST.get('operacion') =='editar':                
            id_proyecto = request.POST.get('id_proyecto')
            usuario=request.POST.get('colaborador')
            proyecto_aux = Proyecto.objects.get(id=id_proyecto)
            usuario_aux= Usuario.objects.get(id=usuario)
            permiso = Tipo_permiso.objects.get(id= request.POST.get('permiso'))
            colab_aux= Colaboracion.objects.get(usuario=usuario_aux, proyecto=proyecto_aux )    
            colab_aux.tipo_permiso =permiso
            colab_aux.save()          
            return redirect('/')

    if request.POST.get('modelo') == 'herramientaProyecto':
        if request.POST.get('operacion') =='agregar':
            herramienta_aux = Herramienta.objects.get(id= request.POST.get('herramienta_id'))
            proyecto_aux = Proyecto.objects.get(id=request.POST.get('id_proyecto'))

            if Herramienta_proyecto.objects.filter(herramienta=herramienta_aux, proyecto=proyecto_aux ).exists():
                var='no pasa nada'
            else:
                Herramienta_proyecto.objects.create(herramienta=herramienta_aux, proyecto=proyecto_aux ) 
                

        if request.POST.get('operacion') =='borrar':
                id_herr =  request.POST.get('herramienta_id')
                id_proy = request.POST.get('id_proyecto')
                herramienta_aux = Herramienta.objects.get(id=id_herr)
                proyecto_aux = Proyecto.objects.get(id=id_proy)

                herr_pro_aux = Herramienta_proyecto.objects.get(herramienta=herramienta_aux, proyecto=proyecto_aux )
                herr_pro_aux.delete()

    if request.POST.get('modelo') == 'segmento':    
        if request.POST.get('operacion') =='crear':  
            proy_aux= Proyecto.objects.get(id=request.POST.get('id_proyecto') )

            #para determinar numero de segmento
            num_segmentos= Segmento.objects.filter(proyecto=proy_aux).count()

            # tipo texto 
            if request.POST.get('tipo_segmento')=='texto':
                tipo_segmento_aux = Tipo_segmento.objects.get(nombre_segmento='texto')
                nuevo_segmento= Segmento.objects.create(
                    proyecto=proy_aux,
                    numero_segmento= (num_segmentos+1),

personas/templates/personas/base.html
{% load static %}


<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


    <!-- css del proyecto -->
    <link rel="stylesheet" href="{% static 'css/estilo3.css' %}">

    {% block librerias %}

    {% endblock %}

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">


    <!-- pal modal-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

 

    <title>PROJECT SHOWCASE</title>
  </head>



  <body>
    
    <div class="container">

      <div class="row bg-light">
          <!--banner -->    
          <div class="col-md-9">                                    
            <!-- Image and text -->  
            <div class="row justify-content-md-center  align-items-center">

                <div class="col-6">
                    <img src="https://media1.tenor.com/images/f57bd258ada9846ed6102f9f06780ede/tenor.gif?itemid=13995867.gif" width="160" height="130" class="d-inline-block align-top" alt="">
                </div>

                <div class="col-6 ">
                    <h4>PROJECT SHOWCASE</h4>
                </div>

            </div>                                  
          </div>

          <!-- sesion -->
          <div class="col-md-3">            
           {% block sesion_avatar %}
           {% endblock %}
          </div>
      </div>


      <!-- navigation bar-->
      <div class="row">
          
          <div class="col-12">
            <nav class="navbar navbar-expand-lg navbar-light bg-secondary text-white">
              <a class="navbar-brand text-white" href="#">Menu</a>
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
            
              <div class="collapse navbar-collapse" id="navbarSupportedContent">                
                <ul class="row navbar-nav mr-auto">

                  <li class="col-4 nav-item">
                    <a class="nav-link text-white" href="{% url 'personas:ultimos_proyectos'%}">Proyectos <span class="sr-only">(current)</span></a>
                  </li>

                  <li class="col-4 nav-item">
                    <a class="nav-link text-white" href="{% url 'personas:ultimos_perfiles' %}">Personas</a>
                  </li>

                  <li class="col-4 nav-item dropdown">
                    <a class="nav-link text-white dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Informacion
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <a class="dropdown-item" href="#">tema1</a>
                      <a class="dropdown-item" href="#">tema2</a>
                      <a class="dropdown-item" href="#">tema3</a>
                      <a class="dropdown-item" href="#">tema4</a>
                      <!--
                      <div class="dropdown-divider"></div>
                      <a class="dropdown-item" href="#">Something else here</a>-->
                    </div>
                  </li>
                 
                </ul>
              </div>
          </div>
      </div>



      <!-- contenido y perfil-->
      <div class="row">
        <div class="col-md-9 order-lg-first order-md-last  order-sm-12  order-12">
            {% block contenido %}
            {% endblock %}
        </div>

        <div class="col-md-3 order-lg-last order-md-first order-sm-1  order-1">
            {% block sesion %}
            {% endblock %}

            {% block perfil %}
            {% endblock %}
        </div>
      </div>

     

<!-- footer-->
      <div class="row justify-content-md-center navbar navbar-light bg-light">          
          <span class="navbar-text col-sm-auto">
            Desarrollado con Django 2020
        </span>                          
      </div>      

    </div>

    



    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>

personas/templates/personas/busqueda_personas.html
{% extends 'personas/inicio.html' %}
  
    {% block contenido %}

            <!-- seccion de busqueda-->
            <div class="row justify-content-md-center">
              <div class="col-auto">
                  <h2>¿Buscas a alguien?... </h2>

              </div>
            </div>

     
            <form action="{% url 'personas:resultado_busqueda_personas'  %}" class="row justify-content-md-center" method="POST" class="post-form" autocomplete="off" >{% csrf_token %}
              <div class="col-md-6">
                <input class="form-control my-4 mr-sm-2" id="texto_busqueda" type="search" name="texto_busqueda" placeholder="Escribe aqui para buscar" aria-label="Search">
                <input type="hidden" id="operacion" name="operacion" value="busqueda"> 
              </div>
              <div class="col-md-2">    
                <button class="btn btn-outline-success my-4 mr-sm-2 btn-primary " type="submit">Buscar</button>
              </div>
            </form>

            {% block listado_personas %}              
            {% endblock %}

    {% endblock %}

personas/templates/personas/busqueda_proyectos.html
{% extends 'personas/inicio.html' %}

{% block contenido%}

    <!-- seccion de busqueda-->
    <div class="row justify-content-md-center">
        <div class="col-auto">
            <h2>¿Buscas algun tema interesante?</h2>
        </div>
    </div>
    
    
    <form action="{% url 'personas:resultado_busqueda_proyectos'  %}" class="row justify-content-md-center" method="POST" class="post-form"  autocomplete="off">{% csrf_token %}
        <div class="col-md-6">
        <input class="form-control my-4 mr-sm-2" id="texto_busqueda" name="texto_busqueda" type="search" placeholder="Escribe aqui para buscar" aria-label="Search" required>
        <input type="hidden" id="operacion" name="operacion" value="busqueda">        
        </div>
        <div class="col-md-2">
        <button class="btn btn-outline-success my-4 mr-sm-2 btn-primary " type="submit">Buscar</button>
        </div>
    </form>


    {% block listado_proyectos %}
    {% endblock %}
  
  
  {% endblock %}
  

personas/templates/personas/crear_cuenta.html
{% extends 'personas/inicio.html' %}



{% block contenido %}
<form method="POST" class="post-form"  autocomplete="off" >{% csrf_token %}


    <div class="row panel justify-content-md-center">
     
            <div class="col-auto">
                <h3>Datos de usuario </h3>
            </div>                              
 
    </div>




  <div class="row ">  
                     
          <div class="col-md-6 form-group">
            <label for="exampleInputEmail1"></label>
            <input type="text" class="form-control" name="nombre1" id="nombre1" aria-describedby="emailHelp" placeholder="Primer nombre">      
          </div>

          <div class="col-md-6 form-group">
            <label for="exampleInputEmail1"></label>
            <input type="text" class="form-control" name="nombre2" id="nombre2" aria-describedby="emailHelp" placeholder="Segundo nombre">      
            <small class="text-success">opcional</small>
          </div>
          
          <div class="col-md-6 form-group">
            <label for="exampleInputEmail1"></label>
            <input type="text" class="form-control" name="apellido1" id="apellido1" aria-describedby="emailHelp" placeholder="Primer apellido">      
          </div>

          <div class="col-md-6 form-group">
            <label for="exampleInputEmail1"></label>
            <input type="text" class="form-control" name="apellido2"  id="apellido2" aria-describedby="emailHelp" placeholder="Segundo apellido">      
            <small class="text-success">opcional</small>
          </div>

          <div class="col-md-6 form-group">
            <label for="exampleInputPassword1"></label>
            <input type="email" class="form-control" name="correo" id="correo" placeholder="email">
          </div>

          <div class="col-md-4 form-group">
            <label for="exampleInputPassword1"></label>
            <input type="text" class="form-control" name="rut" id="rut" placeholder="rut">
            <small class="text-dark">sin puntos ni digito verificador</small>
          </div>

          <div class="col-md-2 form-group">
            <label for="exampleInputPassword1"></label>
            <input type="text" class="form-control" name="dv" id="dv" placeholder="dv">
          </div>
       
                    

          <div class="col-6 form-group">
            <label for="exampleInputPassword1">Fecha Nacimiento</label>
            <input type="date" class="form-control" name="fecha_nacimiento" id="fecha_nacimiento" placeholder="password">
            <small>opcional</small>
          </div>

                           
  </div>

      <div class="row panel justify-content-md-center">        
        <div class="col-auto">
            <h3>Credenciales</h3>
        </div>                              
      </div>

      <div class="row">

            <div class="col-md-6 form-group">
              <label for="exampleInputPassword1">Usuario</label>
              <input type="text" class="form-control" name="user_name" id="user_name" placeholder="user name">
            </div>

            
            <div class="col-md-6 form-group">
              <label for="exampleInputPassword1">Contraseña</label>
              <input type="password" class="form-control" name="password" id="password" placeholder="password">
            </div>

      </div>




      <button type="submit" class="btn btn-primary">Confirmar</button>

</form>

{% endblock %}

personas/templates/personas/listar_personas.html
{% extends 'personas/busqueda_personas.html' %}

{% block listado_personas%}

    <!-- seccion de titulo-->
   <div class="row justify-content-md-center" id="prueba_coso">
    <div class="col-auto">
        <h2>{{titulo}}</h2>      
    </div>
  </div>



{% if lista_usuarios %}
    {% for u in lista_usuarios %}
        {% for p in lista_perfiles %}
            {% if p.usuario == u %}
            <div class="card text-center bg-info">

                <div class="card-header bg-dark text-white">
                <strong>{{u.nombre1}} {{u.apellido1}}</strong>
                </div>
        
                <div class=" card-body">
        
                    <div class="row">
                        <div class="col-md-3">
                            {% if p.retrato %}
                                <img  src="{{p.retrato.thumbnail.url}}" class="img-circle " alt="...">
                            {% else %}
                                <img  src="https://cdn.icon-icons.com/icons2/1508/PNG/512/systemusers_104569.png" width="100" height="100" class="img-circle " alt="...">
                            {% endif%}                                      
                        </div>
        
                        <div class="col-md-6">
                            <div class="row">
                                <div class="col-12 text-white">
                                    <span class="lead">''</span>
                                        {{p.descripcion}}
                                    <span class="lead">''</span>
                                </div>

                                <div class="col-12 text-white">
                                    estudió <i><strong><span class="text-warning">{{p.carrera}}</span></strong></i> en  <i><strong><span class="text-warning">{{p.alma_mater}}</span></strong></i>
                                </div>

                            </div>
                        </div>
        
                        <div class="col-md-3">
                           <div class="row">
                                <div class="col-12 my-2 mr-sm-2 text-white">
                                    <img class="icon" data-toggle="tooltip" data-placement="right" title="Proyectos subidos" src="https://www.flaticon.es/svg/static/icons/svg/2344/2344168.svg" alt="Proyectos subidos">
                                    {% for t in tupla_datos %}
                                        {% if u == t.0 %}
                                            {{t.1}}
                                        {% endif %}
                                    {% endfor%}
                                </div>

                                <div class="col-12 my-2 mr-sm-2 text-white">                                        
                                    <img class="icon"  data-toggle="tooltip" data-placement="right" title="Colaboraciones" src="https://www.flaticon.com/svg/static/icons/svg/36/36178.svg" alt="Colaboraciones">  
                                    {% for t in tupla_datos %}
                                        {% if u == t.0 %}
                                            {{t.2}}
                                        {% endif %}
                                    {% endfor%}
                                </div>
                           </div>                              
                        </div>
                    </div>
        
                    <div class="row">
                        <div class="col-md-12">
                            <a href="{% url 'personas:listado_proyectos_usuario' u.id %}" class="btn btn-dark">ver proyectos</a>
                        </div>
                    </div>
                </div>
        
                <div class="card-footer text-white ">
                    <div class="row">
                        <div class="col-12">
                            Creo su perfil en:  <strong><i>{{p.fecha_creacion}}</i></strong> 
                        </div>                                                      
                    </div>           
                </div>
        
            </div>
            <br><br>
            {% endif %}
        {% endfor %}
    {% endfor %}
{% else %}
    No se encontraron usuarios 
{% endif %}




{% endblock%}